# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.6
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: r.alfaro1882@gmail.com
author_name: yisuscoin
preset_name: starter
project_name: Junta_de_dinero
